Vagrant.configure("2") do |config|
  config.vm.define "mysql_server" do |mysql_server|
    # BOX CONFIGURATION
    mysql_server.vm.box = "bento/ubuntu-22.04"

    # NETWORKING CONFIGURATION
    mysql_server.vm.network "forwarded_port", guest: 80, host: 8080  # http
    mysql_server.vm.network "forwarded_port", guest: 3306, host: 3369  # mysql
    mysql_server.vm.network "private_network", type: "static", ip: "192.168.58.23"

    # PROVIDER CONFIGURATION
    mysql_server.vm.provider "virtualbox" do |vb|
      #  vb.gui = false
      #  vb.memory = "1024"
      #  vb.cpus = 2
    end

    # PROVISIONING CONFIGURATION
    mysql_server.vm.provision "shell", inline: <<-SHELL
      # Set environment variable to avoid dpkg preconfigure warnings
      export DEBIAN_FRONTEND=noninteractive
      # export MYSQL_PWD='rootpass'
      # Install necessary packages
      sudo apt-get update
      sudo apt-get install -y apt-utils net-tools iputils-ping traceroute nano vim openssh-server ufw
      sudo apt-get install -y mysql-server

      # Enable SSH service
      sudo systemctl enable ssh --now
      sudo systemctl start ssh

      # Apply network settings
      sudo ufw allow ssh
      sudo ufw --force enable

      # MySQL Configuration

      # Set MySQL root password and install without prompting
      #sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password rootpass'
      #sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password rootpass'

      # Restart MySQL to apply settings
      sudo systemctl restart mysql

      # Allow remote access to MySQL
      #sudo sed -i "s/bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
      sudo systemctl restart mysql

      # Create database and user for 'coffee_user'
      mysql -u root -prootpass -e "CREATE USER IF NOT EXISTS 'coffee_user'@'localhost' IDENTIFIED BY 'coffeeaddict';"
      mysql -u root -prootpass -e "CREATE DATABASE IF NOT EXISTS coffee_db;"
      mysql -u root -prootpass -e "GRANT ALL PRIVILEGES ON coffee_db.* TO 'coffee_user'@'localhost';"
      mysql -u root -prootpass -e "FLUSH PRIVILEGES;"

      # Restart MySQL to apply all changes
      sudo systemctl restart mysql
    SHELL
  end
end